[changelog]
header = ""
body = """
{% if version %}## Release {{ version }}
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}

{% for commit in commits %}\
- {{ commit.message | split(pat="\n") | first | split(pat=": ") | slice(start=1) | join(sep=": ") | upper_first }} ({{ commit.id }})
{% endfor %}
{% endfor %}\
"""
footer = ""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "^security", group = "<!-- 0 -->🔒 Security" },
    { message = "^feat", group = "<!-- 1 -->✨ Features" },
    { message = "^fix", group = "<!-- 2 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 3 -->⚡ Performance" },
    { message = "^doc", group = "<!-- 4 -->📚 Documentation" },
    { message = "^chore", group = "<!-- 5 -->🔧 Chores" },
    { message = "^refactor", group = "<!-- 6 -->♻️ Refactor" },
]
# false = include commits that don't match any parser (as ungrouped)
# true = exclude commits that don't match any parser (only release-worthy commits)
filter_commits = true
tag_pattern = "v[0-9].*"
